### ISSUE TITLE
Design and implement a well defined format for logged data 

### ISSUE THREAD

**Issue by theFestest** [GeorgetownMakerHubOrg/air-quality#12]
With the inclusion of logging to disk with, perhaps occasional, uploads to the internet. We will want to have a well defined and easily extensible format for our data points. For example, we will want the format to always include certain base parameters such as the "serial" and timestamp, but be able to optionally include a variety of sensor parameters. Some sort JSON dictionary seems workable with these requirements and relatively easy? That's my first thought, I'd be interested in suggestions for those more knowledgeable.

**Comment by fpgirard** [comment]
Ok, using email to document ideas in git is suboptimal.   Like Michael
points out, it’s also too public.   I really don’t want to post my
suggestion here but it’s good.
P

On July 11, 2019 at 9:26:44 PM, Michael Bartholic (notifications@github.com)
wrote:

With the inclusion of logging to disk with, perhaps occasional, uploads to
the internet. We will want to have a well defined and easily extensible
format for our data points. For example, we will want the format to always
include certain base parameters such as the "serial" and timestamp, but be
able to optionally include a variety of sensor parameters. Some sort JSON
dictionary seems workable with these requirements and relatively easy?
That's my first thought, I'd be interested in suggestions for those more
knowledgeable.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GeorgetownMakerHubOrg/air-quality/issues/12?email_source=notifications&email_token=ADERE5T2EVVJ37TOQF3PNLDP67MTLA5CNFSM4IB5O3FKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G6YRJOA>,
or mute the thread

**Comment by fpgirard** [comment]
Let's talk to Krista at OpenAQ and work together to agree what the proper sensors and data and format should be for us to their Tier II supplier.

**Comment by theFestest** [comment]
I agree that this is a conversation that we should get moving.

For the immediate term, I think we can refer to their documentation of the [formats](https://github.com/openaq/openaq-data-format) they provide outwardly. Using this and referring to the structure and capabilities of their [API](https://github.com/openaq/openaq-api) should be a good start. We ought to be able to learn a thing or two in terms of data acquisition and workflows from them.
