### ISSUE TITLE
Upgrade script for MacOS, Linux and Windows

### ISSUE THREAD

**Issue by fpgirard** [GeorgetownMakerHubOrg/air-quality#17]
The Kathmandu GUAQ has shipped without network/Wifi credentials.  We will need to upgrade this unit on site.  An upgrade script that uses ampy to put files to a GUAQ that has the supported micropython version (for 905, this is 1.11) is needed.   If we can avoid having to use esptool to flash uP, we will reduce the number of problems.  

The onsite team will have to put the unit into 'upgrade' mode to prevent a wake/sleep cycle that prohibits ampy from working properly.    The other alternative is to teach this team how to use the WebREPL interface to upload specific files (like config.py).

**Comment by cmpadden** [comment]
I am working on this in pull request #26.

So far I have made it so that the target device can be specified as a command line argument, and I have introduced the optional argument `reinstall` which will conditionally trigger the erasing of the device, and re-flashing of MicroPython. If the `reinstall` argument is not specified, then the code will be uploaded with `Ampy` per usual.
