### ISSUE TITLE
On-board Sensor Information Storage for Network Outtages

### ISSUE THREAD

**Issue by cmpadden** [GeorgetownMakerHubOrg/air-quality#8]
For scenarios where the networking is less than ideal, we should store sensor measurements on-board and then upload missing data when the network has come back online.

**Comment by theFestest** [comment]
I agree. This is in the hardware pipeline and will need to be supported optionally (if the hardware is present) because there are currently monitors in use which do not have non-volatile memory. It would be ideal for us to be able to keep track of the last successful post and continue logging when the network is unavailable. That way even locations which are far away from a network, could be brought into network range (either bringing a hotspot to the monitor or taking the monitor into a wifi network) occasionally to offload data.

**Comment by fpgirard** [comment]
From a hardware perspective, we’re in pretty good shape if we use the Lolin ESP32 Pro board.   It’s < $2 more expensive and includes a microSD slot.

How do we record that we will need to modify the baseplate and laser cut an additional mounting hole for this board?  The other mounting holes are the same.



On July 11, 2019 at 12:14:03 PM, Michael Bartholic (notifications@github.com) wrote:

I agree. This is in the hardware pipeline and will need to be supported optionally (if the hardware is present) because there are currently monitors in use which do not have non-volatile memory. It would be ideal for us to be able to keep track of the last successful post and continue logging when the network is unavailable. That way even locations which are far away from a network, could be brought into network range (either bringing a hotspot to the monitor or taking the monitor into a wifi network) occasionally to offload data.

**Comment by theFestest** [comment]
Short term, I would say make a document that can be included in the limited access GUAQ Google drive folder that I'm keeping where we can list hardware to-dos/changes. 

Longer-term, we can investigate using a tool such as [Jira](https://www.atlassian.com/software/jira) (there are many available [options](https://en.wikipedia.org/wiki/Comparison_of_issue-tracking_systems)) to keep track of all types of to-do type work as well as incorporating tasking. 

I envision we can eventually include our hardware diagrams and specifications as a folder in the repository, that way they can easily be distributed open-source along with the code. Thoughts?
